development:
  adapter: mysql2
  database: voteme
  username: root
  password: password
  host: localhost
test:
  adapter: mysql2
  database: voteme_test
  username: root
  password: password
  host: localhost
production:
  adapter: mysql2
  database: voteme
  username: root
  password:
  host: localhost
