development:
  adapter: postgresql
  database: voteme
  username: root
  password: postgres
  host: localhost
  port: 5432
test:
  adapter: postgresql
  database: voteme_test
  username: root
  password: postgres
  host: localhost
  port: 5432
production:
  adapter: postgresql
  database: voteme
  username: root
  password:
  host: localhost
  port: 5432
